SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `fa_staff_profile` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '后台账号',
  `account` varchar(50) NOT NULL DEFAULT '' COMMENT '登录账号',
  `employee_no` varchar(30) NOT NULL DEFAULT '' COMMENT '工号',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `title` varchar(100) NOT NULL DEFAULT '' COMMENT '岗位',
  `department` varchar(100) NOT NULL DEFAULT '' COMMENT '部门',
  `role_key` enum('admin','finance','project','operations','service','tech','viewer') NOT NULL DEFAULT 'viewer' COMMENT '角色组:admin=管理员,finance=财务,project=项目,operations=运营,service=客服,tech=技术,viewer=只读',
  `permissions_json` text COMMENT '附加权限JSON',
  `phone` varchar(20) NOT NULL DEFAULT '' COMMENT '手机号',
  `email` varchar(100) NOT NULL DEFAULT '' COMMENT '邮箱',
  `hire_date` date DEFAULT NULL COMMENT '入职日期',
  `manager_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '直属上级旧ID',
  `manager_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '直属上级后台账号',
  `status` enum('active','inactive') NOT NULL DEFAULT 'active' COMMENT '状态:active=在职,inactive=停用',
  `last_login_at` datetime DEFAULT NULL COMMENT '最近登录时间',
  `notes` text COMMENT '备注',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_staff_profile_legacy_id` (`legacy_id`),
  UNIQUE KEY `uk_staff_profile_account` (`account`),
  KEY `idx_staff_profile_admin_id` (`admin_id`),
  KEY `idx_staff_profile_role_key` (`role_key`),
  KEY `idx_staff_profile_department` (`department`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工档案';

CREATE TABLE IF NOT EXISTS `fa_staff_audit` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联后台账号',
  `actor_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '操作人后台账号',
  `actor_name` varchar(50) NOT NULL DEFAULT '' COMMENT '操作人',
  `module` varchar(50) NOT NULL DEFAULT '' COMMENT '所属模块',
  `action` varchar(50) NOT NULL DEFAULT '' COMMENT '动作',
  `object_type` varchar(50) NOT NULL DEFAULT '' COMMENT '对象类型',
  `object_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '对象旧ID',
  `content` text COMMENT '日志内容',
  `ip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP',
  `useragent` varchar(255) NOT NULL DEFAULT '' COMMENT 'UserAgent',
  `happened_at` datetime DEFAULT NULL COMMENT '发生时间',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_staff_audit_legacy_id` (`legacy_id`),
  KEY `idx_staff_audit_module` (`module`),
  KEY `idx_staff_audit_actor_admin_id` (`actor_admin_id`),
  KEY `idx_staff_audit_happened_at` (`happened_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='人员操作留痕';

CREATE TABLE IF NOT EXISTS `fa_project` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `name` varchar(150) NOT NULL DEFAULT '' COMMENT '项目名称',
  `client` varchar(150) NOT NULL DEFAULT '' COMMENT '客户名称',
  `owner` varchar(50) NOT NULL DEFAULT '' COMMENT '项目负责人',
  `owner_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '负责人后台账号',
  `status` enum('planning','active','delivery','completed','paused','closed') NOT NULL DEFAULT 'planning' COMMENT '项目状态:planning=规划中,active=执行中,delivery=交付中,completed=已完成,paused=暂停,closed=已关闭',
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium' COMMENT '优先级:low=低,medium=中,high=高,urgent=紧急',
  `budget` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '预算金额',
  `start_date` date DEFAULT NULL COMMENT '开始日期',
  `due_date` date DEFAULT NULL COMMENT '截止日期',
  `description` text COMMENT '项目说明',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_legacy_id` (`legacy_id`),
  KEY `idx_project_owner_admin_id` (`owner_admin_id`),
  KEY `idx_project_status` (`status`),
  KEY `idx_project_due_date` (`due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目台账';

CREATE TABLE IF NOT EXISTS `fa_project_task` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '项目旧ID',
  `project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属项目',
  `title` varchar(150) NOT NULL DEFAULT '' COMMENT '任务名称',
  `assignee` varchar(50) NOT NULL DEFAULT '' COMMENT '执行人',
  `assignee_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '执行人后台账号',
  `status` enum('todo','doing','review','done','blocked','overdue') NOT NULL DEFAULT 'todo' COMMENT '任务状态:todo=待处理,doing=进行中,review=待验收,done=已完成,blocked=阻塞,overdue=已逾期',
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium' COMMENT '优先级:low=低,medium=中,high=高,urgent=紧急',
  `due_date` date DEFAULT NULL COMMENT '截止日期',
  `estimate_hours` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '预估工时',
  `actual_hours` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '实际工时',
  `notes` text COMMENT '备注',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_task_legacy_id` (`legacy_id`),
  KEY `idx_project_task_project_id` (`project_id`),
  KEY `idx_project_task_assignee_admin_id` (`assignee_admin_id`),
  KEY `idx_project_task_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目任务';

CREATE TABLE IF NOT EXISTS `fa_finance_transaction` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `transaction_date` date DEFAULT NULL COMMENT '记账日期',
  `type` enum('income','expense') NOT NULL DEFAULT 'expense' COMMENT '收支类型:income=收入,expense=支出',
  `category` varchar(100) NOT NULL DEFAULT '' COMMENT '科目分类',
  `counterparty` varchar(150) NOT NULL DEFAULT '' COMMENT '往来对象',
  `amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '金额',
  `payment_method` enum('bank','wechat','alipay','cash','other') NOT NULL DEFAULT 'bank' COMMENT '支付方式:bank=银行,wechat=微信,alipay=支付宝,cash=现金,other=其他',
  `project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '项目旧ID',
  `project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联项目',
  `notes` text COMMENT '备注',
  `attachment_ids_json` text COMMENT '附件ID列表JSON',
  `record_created_at` datetime DEFAULT NULL COMMENT '业务创建时间',
  `record_updated_at` datetime DEFAULT NULL COMMENT '业务更新时间',
  `created_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人旧ID',
  `created_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建人后台账号',
  `created_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `updated_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人旧ID',
  `updated_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新人后台账号',
  `updated_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '更新人',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_finance_transaction_legacy_id` (`legacy_id`),
  KEY `idx_finance_transaction_project_id` (`project_id`),
  KEY `idx_finance_transaction_type` (`type`),
  KEY `idx_finance_transaction_transaction_date` (`transaction_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='财务流水';

CREATE TABLE IF NOT EXISTS `fa_finance_invoice` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `kind` enum('receivable','payable') NOT NULL DEFAULT 'receivable' COMMENT '单据类型:receivable=应收,payable=应付',
  `title` varchar(150) NOT NULL DEFAULT '' COMMENT '单据标题',
  `counterparty` varchar(150) NOT NULL DEFAULT '' COMMENT '往来对象',
  `amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '金额',
  `due_date` date DEFAULT NULL COMMENT '到期日期',
  `status` enum('pending','partial','paid','overdue','cancelled') NOT NULL DEFAULT 'pending' COMMENT '单据状态:pending=待处理,partial=部分完成,paid=已完成,overdue=已逾期,cancelled=已作废',
  `project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '项目旧ID',
  `project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联项目',
  `notes` text COMMENT '备注',
  `attachment_ids_json` text COMMENT '附件ID列表JSON',
  `record_created_at` datetime DEFAULT NULL COMMENT '业务创建时间',
  `record_updated_at` datetime DEFAULT NULL COMMENT '业务更新时间',
  `created_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人旧ID',
  `created_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建人后台账号',
  `created_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `updated_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人旧ID',
  `updated_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新人后台账号',
  `updated_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '更新人',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_finance_invoice_legacy_id` (`legacy_id`),
  KEY `idx_finance_invoice_project_id` (`project_id`),
  KEY `idx_finance_invoice_kind` (`kind`),
  KEY `idx_finance_invoice_due_date` (`due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='应收应付';

CREATE TABLE IF NOT EXISTS `fa_app_project` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `name` varchar(150) NOT NULL DEFAULT '' COMMENT '运营项目',
  `project_type` varchar(30) NOT NULL DEFAULT 'app' COMMENT '项目类型',
  `app_name` varchar(150) NOT NULL DEFAULT '' COMMENT 'APP名称',
  `app_version` varchar(50) NOT NULL DEFAULT '' COMMENT '当前版本',
  `lifecycle_stage` enum('idea','validation','launch','growth','retention','mature','sunset') NOT NULL DEFAULT 'validation' COMMENT '生命周期:idea=构思,validation=验证,launch=上线,growth=增长,retention=留存,mature=成熟,sunset=下线',
  `business_line` varchar(100) NOT NULL DEFAULT '' COMMENT '业务线',
  `manager` varchar(50) NOT NULL DEFAULT '' COMMENT '运营负责人',
  `manager_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '运营负责人后台账号',
  `client_owner` varchar(100) NOT NULL DEFAULT '' COMMENT '业务负责人',
  `core_metric` varchar(100) NOT NULL DEFAULT '' COMMENT '核心指标',
  `status` enum('planning','running','paused','completed','archived') NOT NULL DEFAULT 'planning' COMMENT '项目状态:planning=规划中,running=执行中,paused=暂停,completed=已完成,archived=已归档',
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium' COMMENT '优先级:low=低,medium=中,high=高,urgent=紧急',
  `budget` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '预算',
  `actual_cost` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '实际成本',
  `start_date` date DEFAULT NULL COMMENT '开始日期',
  `end_date` date DEFAULT NULL COMMENT '结束日期',
  `target` text COMMENT '目标说明',
  `channel` varchar(255) NOT NULL DEFAULT '' COMMENT '运营渠道',
  `project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '交付项目旧ID',
  `project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联交付项目',
  `description` text COMMENT '项目说明',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_project_legacy_id` (`legacy_id`),
  KEY `idx_app_project_project_id` (`project_id`),
  KEY `idx_app_project_manager_admin_id` (`manager_admin_id`),
  KEY `idx_app_project_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='APP运营项目';

CREATE TABLE IF NOT EXISTS `fa_app_milestone` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `app_project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'APP项目旧ID',
  `app_project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属APP项目',
  `title` varchar(150) NOT NULL DEFAULT '' COMMENT '里程碑',
  `owner` varchar(50) NOT NULL DEFAULT '' COMMENT '负责人',
  `owner_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '负责人后台账号',
  `due_date` date DEFAULT NULL COMMENT '节点日期',
  `status` enum('pending','doing','review','done','blocked') NOT NULL DEFAULT 'pending' COMMENT '状态:pending=待开始,doing=进行中,review=待确认,done=已完成,blocked=阻塞',
  `progress` int(11) NOT NULL DEFAULT '0' COMMENT '进度%',
  `deliverable` varchar(255) NOT NULL DEFAULT '' COMMENT '交付物',
  `notes` text COMMENT '备注',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_milestone_legacy_id` (`legacy_id`),
  KEY `idx_app_milestone_app_project_id` (`app_project_id`),
  KEY `idx_app_milestone_owner_admin_id` (`owner_admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运营里程碑';

CREATE TABLE IF NOT EXISTS `fa_app_report` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `app_project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'APP项目旧ID',
  `app_project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属APP项目',
  `report_date` date DEFAULT NULL COMMENT '周报日期',
  `owner` varchar(50) NOT NULL DEFAULT '' COMMENT '提交人',
  `owner_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '提交人后台账号',
  `summary` text COMMENT '本周概述',
  `result` text COMMENT '阶段结果',
  `next_actions` text COMMENT '下步动作',
  `blockers` text COMMENT '阻塞事项',
  `record_created_at` datetime DEFAULT NULL COMMENT '业务创建时间',
  `record_updated_at` datetime DEFAULT NULL COMMENT '业务更新时间',
  `created_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人旧ID',
  `created_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建人后台账号',
  `created_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `updated_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人旧ID',
  `updated_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新人后台账号',
  `updated_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '更新人',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_report_legacy_id` (`legacy_id`),
  KEY `idx_app_report_app_project_id` (`app_project_id`),
  KEY `idx_app_report_owner_admin_id` (`owner_admin_id`),
  KEY `idx_app_report_report_date` (`report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目汇报';

CREATE TABLE IF NOT EXISTS `fa_app_risk` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `app_project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'APP项目旧ID',
  `app_project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属APP项目',
  `title` varchar(150) NOT NULL DEFAULT '' COMMENT '风险标题',
  `type` enum('risk','issue','change','dependency') NOT NULL DEFAULT 'risk' COMMENT '风险类型:risk=风险,issue=问题,change=变更,dependency=依赖',
  `level` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium' COMMENT '风险等级:low=低,medium=中,high=高,critical=严重',
  `status` enum('open','tracking','resolved','closed') NOT NULL DEFAULT 'open' COMMENT '处理状态:open=待处理,tracking=跟进中,resolved=已解决,closed=已关闭',
  `owner` varchar(50) NOT NULL DEFAULT '' COMMENT '负责人',
  `owner_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '负责人后台账号',
  `due_date` date DEFAULT NULL COMMENT '处理截止',
  `impact` text COMMENT '影响范围',
  `action_plan` text COMMENT '处理方案',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_risk_legacy_id` (`legacy_id`),
  KEY `idx_app_risk_app_project_id` (`app_project_id`),
  KEY `idx_app_risk_owner_admin_id` (`owner_admin_id`),
  KEY `idx_app_risk_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运营风险';

CREATE TABLE IF NOT EXISTS `fa_app_tech_ticket` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `app_project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'APP项目旧ID',
  `app_project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属APP项目',
  `project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '交付项目旧ID',
  `project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联交付项目',
  `title` varchar(150) NOT NULL DEFAULT '' COMMENT '研发待办',
  `type` enum('bug','improvement','upgrade','task') NOT NULL DEFAULT 'bug' COMMENT '待办类型:bug=Bug,improvement=优化,upgrade=升级,task=任务',
  `status` enum('pending','processing','testing','ready','done','closed') NOT NULL DEFAULT 'pending' COMMENT '处理状态:pending=待处理,processing=处理中,testing=测试中,ready=待发布,done=已完成,closed=已关闭',
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium' COMMENT '优先级:low=低,medium=中,high=高,urgent=紧急',
  `severity` enum('low','medium','high','blocker') NOT NULL DEFAULT 'medium' COMMENT '严重级别:low=低,medium=中,high=高,blocker=阻断',
  `source` enum('operations','product','customer','sales','service') NOT NULL DEFAULT 'operations' COMMENT '来源:operations=运营,product=产品,customer=客户,sales=销售,service=客服',
  `app_module` varchar(100) NOT NULL DEFAULT '' COMMENT 'APP模块',
  `app_version` varchar(50) NOT NULL DEFAULT '' COMMENT '影响版本',
  `owner` varchar(50) NOT NULL DEFAULT '' COMMENT '负责人',
  `owner_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '负责人后台账号',
  `reporter` varchar(50) NOT NULL DEFAULT '' COMMENT '提出人',
  `reporter_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '提出人后台账号',
  `due_date` date DEFAULT NULL COMMENT '计划完成日期',
  `impact` text COMMENT '影响说明',
  `solution_plan` text COMMENT '解决方案',
  `estimate_hours` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '预估工时',
  `actual_hours` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '实际工时',
  `notes` text COMMENT '备注',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_tech_ticket_legacy_id` (`legacy_id`),
  KEY `idx_app_tech_ticket_app_project_id` (`app_project_id`),
  KEY `idx_app_tech_ticket_project_id` (`project_id`),
  KEY `idx_app_tech_ticket_owner_admin_id` (`owner_admin_id`),
  KEY `idx_app_tech_ticket_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='研发联动';

CREATE TABLE IF NOT EXISTS `fa_app_issue` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `ticket_no` varchar(50) NOT NULL DEFAULT '' COMMENT '问题单号',
  `source` enum('customer','training','sales','operations','other') NOT NULL DEFAULT 'customer' COMMENT '来源:customer=客户,training=培训,sales=销售,operations=运营,other=其他',
  `customer` varchar(150) NOT NULL DEFAULT '' COMMENT '客户名称',
  `contact_name` varchar(50) NOT NULL DEFAULT '' COMMENT '联系人',
  `contact_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `channel` enum('wechat','phone','email','app','onsite','other') NOT NULL DEFAULT 'wechat' COMMENT '反馈渠道:wechat=微信,phone=电话,email=邮件,app=应用内,onsite=现场,other=其他',
  `category` enum('bug','usage','billing','feature','training','other') NOT NULL DEFAULT 'usage' COMMENT '问题分类:bug=Bug,usage=使用咨询,billing=账单,feature=功能建议,training=培训,other=其他',
  `title` varchar(150) NOT NULL DEFAULT '' COMMENT '问题标题',
  `summary` text COMMENT '问题概述',
  `status` enum('new','processing','waiting_customer','escalated','resolved','closed') NOT NULL DEFAULT 'new' COMMENT '处理状态:new=新建,processing=处理中,waiting_customer=待客户确认,escalated=已升级,resolved=已解决,closed=已关闭',
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium' COMMENT '优先级:low=低,medium=中,high=高,urgent=紧急',
  `assignee` varchar(50) NOT NULL DEFAULT '' COMMENT '受理人',
  `assignee_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '受理人后台账号',
  `opened_at` datetime DEFAULT NULL COMMENT '创建时间',
  `last_follow_up_at` datetime DEFAULT NULL COMMENT '最近跟进',
  `resolve_due_at` datetime DEFAULT NULL COMMENT '承诺解决时间',
  `next_action` text COMMENT '下一步动作',
  `customer_notified` tinyint(1) NOT NULL DEFAULT '0' COMMENT '已回告客户',
  `customer_notified_to` varchar(100) NOT NULL DEFAULT '' COMMENT '回告对象',
  `customer_notified_channel` varchar(30) NOT NULL DEFAULT '' COMMENT '回告方式',
  `customer_notified_at` datetime DEFAULT NULL COMMENT '回告时间',
  `customer_feedback_result` text COMMENT '回告结果',
  `customer_confirmed` tinyint(1) NOT NULL DEFAULT '0' COMMENT '客户已确认',
  `customer_confirmed_at` datetime DEFAULT NULL COMMENT '客户确认时间',
  `customer_confirmation_note` text COMMENT '客户确认说明',
  `app_project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'APP项目旧ID',
  `app_project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属APP项目',
  `project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '交付项目旧ID',
  `project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联交付项目',
  `tech_ticket_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '研发待办旧ID',
  `tech_ticket_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联研发待办',
  `notes` text COMMENT '内部备注',
  `record_created_at` datetime DEFAULT NULL COMMENT '业务创建时间',
  `record_updated_at` datetime DEFAULT NULL COMMENT '业务更新时间',
  `created_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人旧ID',
  `created_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建人后台账号',
  `created_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `updated_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人旧ID',
  `updated_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新人后台账号',
  `updated_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '更新人',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_issue_legacy_id` (`legacy_id`),
  UNIQUE KEY `uk_app_issue_ticket_no` (`ticket_no`),
  KEY `idx_app_issue_app_project_id` (`app_project_id`),
  KEY `idx_app_issue_project_id` (`project_id`),
  KEY `idx_app_issue_tech_ticket_id` (`tech_ticket_id`),
  KEY `idx_app_issue_assignee_admin_id` (`assignee_admin_id`),
  KEY `idx_app_issue_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问题记录';

CREATE TABLE IF NOT EXISTS `fa_app_issue_followup` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `issue_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '问题旧ID',
  `issue_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属问题',
  `type` enum('status','follow_up','internal','leader','release') NOT NULL DEFAULT 'follow_up' COMMENT '跟进类型:status=状态同步,follow_up=跟进,internal=内部备注,leader=领导反馈,release=版本回告',
  `visibility` enum('internal','customer','leader') NOT NULL DEFAULT 'internal' COMMENT '可见范围:internal=内部,customer=客户回告,leader=领导同步',
  `content` text COMMENT '跟进内容',
  `status` varchar(30) NOT NULL DEFAULT '' COMMENT '当前状态',
  `next_action` text COMMENT '下一步动作',
  `record_created_at` datetime DEFAULT NULL COMMENT '业务创建时间',
  `record_updated_at` datetime DEFAULT NULL COMMENT '业务更新时间',
  `created_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人旧ID',
  `created_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建人后台账号',
  `created_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `updated_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人旧ID',
  `updated_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新人后台账号',
  `updated_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '更新人',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_issue_followup_legacy_id` (`legacy_id`),
  KEY `idx_app_issue_followup_issue_id` (`issue_id`),
  KEY `idx_app_issue_followup_created_by_admin_id` (`created_by_admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问题跟进';

CREATE TABLE IF NOT EXISTS `fa_app_release` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `app_project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'APP项目旧ID',
  `app_project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属APP项目',
  `version` varchar(50) NOT NULL DEFAULT '' COMMENT '版本号',
  `title` varchar(150) NOT NULL DEFAULT '' COMMENT '发布标题',
  `status` enum('planned','ready','testing','released','rollback','closed') NOT NULL DEFAULT 'planned' COMMENT '发布状态:planned=待排期,ready=待发布,testing=测试中,released=已发布,rollback=已回滚,closed=已关闭',
  `owner` varchar(50) NOT NULL DEFAULT '' COMMENT '发布负责人',
  `owner_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '负责人后台账号',
  `release_date` date DEFAULT NULL COMMENT '计划发布日期',
  `channel` varchar(100) NOT NULL DEFAULT '' COMMENT '发布范围',
  `tech_ticket_ids_json` text COMMENT '关联研发待办JSON',
  `service_ticket_ids_json` text COMMENT '关联问题记录JSON',
  `verification_summary` text COMMENT '验证结论',
  `customer_sync_status` enum('pending','done','skip') NOT NULL DEFAULT 'pending' COMMENT '客户回告:pending=待回告,done=已回告,skip=无需回告',
  `customer_sync_note` text COMMENT '客户回告说明',
  `release_result` text COMMENT '发布结果',
  `release_notes` text COMMENT '发布说明',
  `rollback_plan` text COMMENT '回滚方案',
  `rollback_ready` tinyint(1) NOT NULL DEFAULT '0' COMMENT '已备回滚方案',
  `notes` text COMMENT '备注',
  `record_created_at` datetime DEFAULT NULL COMMENT '业务创建时间',
  `record_updated_at` datetime DEFAULT NULL COMMENT '业务更新时间',
  `created_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人旧ID',
  `created_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建人后台账号',
  `created_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `updated_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人旧ID',
  `updated_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新人后台账号',
  `updated_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '更新人',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_release_legacy_id` (`legacy_id`),
  KEY `idx_app_release_app_project_id` (`app_project_id`),
  KEY `idx_app_release_owner_admin_id` (`owner_admin_id`),
  KEY `idx_app_release_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='版本发布';

CREATE TABLE IF NOT EXISTS `fa_app_material` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '旧系统ID',
  `app_project_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'APP项目旧ID',
  `app_project_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属APP项目',
  `title` varchar(150) NOT NULL DEFAULT '' COMMENT '资料名称',
  `category` enum('manual','faq','training','script','report','other') NOT NULL DEFAULT 'manual' COMMENT '资料分类:manual=手册,faq=FAQ,training=培训,script=脚本,report=报告,other=其他',
  `owner` varchar(50) NOT NULL DEFAULT '' COMMENT '资料负责人',
  `owner_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '负责人后台账号',
  `version_tag` varchar(50) NOT NULL DEFAULT '' COMMENT '资料版本',
  `applicable_versions` varchar(100) NOT NULL DEFAULT '' COMMENT '适用版本',
  `expires_on` date DEFAULT NULL COMMENT '失效日期',
  `archive_status` enum('active','archived') NOT NULL DEFAULT 'active' COMMENT '归档状态:active=在用,archived=已归档',
  `replacement_material_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '替代资料旧ID',
  `replacement_material_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '替代资料',
  `download_name` varchar(255) NOT NULL DEFAULT '' COMMENT '文件名',
  `download_url` varchar(255) NOT NULL DEFAULT '' COMMENT '下载链接',
  `file_path` varchar(255) NOT NULL DEFAULT '' COMMENT '文件路径',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '文件大小',
  `file_mime` varchar(100) NOT NULL DEFAULT '' COMMENT '文件类型',
  `updated_on` date DEFAULT NULL COMMENT '资料更新日',
  `notes` text COMMENT '资料说明',
  `record_created_at` datetime DEFAULT NULL COMMENT '业务创建时间',
  `record_updated_at` datetime DEFAULT NULL COMMENT '业务更新时间',
  `created_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人旧ID',
  `created_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建人后台账号',
  `created_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `updated_by_legacy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人旧ID',
  `updated_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新人后台账号',
  `updated_by_name` varchar(50) NOT NULL DEFAULT '' COMMENT '更新人',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_material_legacy_id` (`legacy_id`),
  KEY `idx_app_material_app_project_id` (`app_project_id`),
  KEY `idx_app_material_owner_admin_id` (`owner_admin_id`),
  KEY `idx_app_material_archive_status` (`archive_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='内部资料';

CREATE TABLE IF NOT EXISTS `fa_ai_setting` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `provider_name` varchar(100) NOT NULL DEFAULT '' COMMENT '模型供应商',
  `base_url` varchar(255) NOT NULL DEFAULT '' COMMENT '接口地址',
  `api_key` varchar(255) NOT NULL DEFAULT '' COMMENT 'API Key',
  `model` varchar(100) NOT NULL DEFAULT '' COMMENT '模型名称',
  `temperature` decimal(4,2) NOT NULL DEFAULT '0.20' COMMENT '温度',
  `system_prompt` text COMMENT '系统提示词',
  `workspace_json` text COMMENT '工作台配置JSON',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI配置';

CREATE TABLE IF NOT EXISTS `fa_ai_conversation` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `role` enum('system','user','assistant') NOT NULL DEFAULT 'assistant' COMMENT '消息角色:system=系统,user=用户,assistant=助手',
  `content` text COMMENT '消息内容',
  `message_at` datetime DEFAULT NULL COMMENT '消息时间',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_conversation_message_at` (`message_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI会话';
CREATE TABLE IF NOT EXISTS `fa_ai_task` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绠＄悊鍛?',
  `prompt` text COMMENT '鍘熷闂',
  `focus` varchar(30) NOT NULL DEFAULT 'overview' COMMENT '鍒嗘瀽鑼冨洿',
  `preset_key` varchar(60) NOT NULL DEFAULT '' COMMENT '棰勮',
  `setting_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '妯″瀷閰嶇疆',
  `quick_mode` tinyint(1) NOT NULL DEFAULT '1' COMMENT '蹇€熸ā寮?',
  `status` enum('queued','processing','done','failed') NOT NULL DEFAULT 'queued' COMMENT '浠诲姟鐘舵€?',
  `result_json` longtext COMMENT '缁撴灉 JSON',
  `error_message` varchar(500) NOT NULL DEFAULT '' COMMENT '閿欒淇℃伅',
  `started_at` datetime DEFAULT NULL COMMENT '寮€濮嬫椂闂?',
  `finished_at` datetime DEFAULT NULL COMMENT '瀹屾垚鏃堕棿',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_task_admin_status` (`admin_id`,`status`),
  KEY `idx_ai_task_createtime` (`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI鍚庡彴浠诲姟';
ALTER TABLE `fa_business_approval`
  MODIFY COLUMN `object_type` enum('contract','payment_plan','expense_request','purchase_order','payment_request') NOT NULL DEFAULT 'contract' COMMENT '审批对象类型';

CREATE TABLE IF NOT EXISTS `fa_erp_module` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `legacy_id` varchar(64) NOT NULL DEFAULT '',
  `module_key` varchar(50) NOT NULL DEFAULT '',
  `module_name` varchar(100) NOT NULL DEFAULT '',
  `module_type` varchar(20) NOT NULL DEFAULT 'plugin',
  `icon` varchar(50) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `entry_route` varchar(100) NOT NULL DEFAULT '',
  `is_enabled` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `is_locked` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `sort_no` int(10) unsigned NOT NULL DEFAULT '0',
  `updated_at` datetime DEFAULT NULL,
  `created_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0',
  `created_by_name` varchar(50) NOT NULL DEFAULT '',
  `updated_by_admin_id` int(10) unsigned NOT NULL DEFAULT '0',
  `updated_by_name` varchar(50) NOT NULL DEFAULT '',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_module_key` (`module_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 模块中心';
