<?php

declare(strict_types=1);

return [
    'meta' => [
        'company' => '云帆软件',
        'currency' => 'CNY',
        'version' => '1.5.0',
    ],
    'users' => [
        [
            'id' => 'user-1001',
            'account' => 'admin',
            'employee_no' => 'A0001',
            'name' => '陈昊',
            'title' => '系统管理员',
            'department' => '管理部',
            'role' => 'admin',
            'permissions' => [],
            'status' => 'active',
            'phone' => '13800000001',
            'email' => 'admin@yfsoft.local',
            'hire_date' => '2024-01-03',
            'manager_id' => '',
            'password_hash' => password_hash('Admin@123', PASSWORD_DEFAULT),
            'last_login_at' => '',
            'created_at' => '2026-03-01 09:00:00',
            'updated_at' => '2026-03-01 09:00:00',
        ],
        [
            'id' => 'user-1002',
            'account' => 'finance.li',
            'employee_no' => 'F1001',
            'name' => '李妍',
            'title' => '财务主管',
            'department' => '财务部',
            'role' => 'finance',
            'permissions' => ['ai.manage'],
            'status' => 'active',
            'phone' => '13800000002',
            'email' => 'finance.li@yfsoft.local',
            'hire_date' => '2024-04-15',
            'manager_id' => 'user-1001',
            'password_hash' => password_hash('Start@123', PASSWORD_DEFAULT),
            'last_login_at' => '',
            'created_at' => '2026-03-01 09:00:00',
            'updated_at' => '2026-03-01 09:00:00',
        ],
        [
            'id' => 'user-1003',
            'account' => 'pm.zhang',
            'employee_no' => 'P1001',
            'name' => '张敏',
            'title' => '项目经理',
            'department' => '交付部',
            'role' => 'project',
            'permissions' => [],
            'status' => 'active',
            'phone' => '13800000003',
            'email' => 'pm.zhang@yfsoft.local',
            'hire_date' => '2024-06-18',
            'manager_id' => 'user-1001',
            'password_hash' => password_hash('Start@123', PASSWORD_DEFAULT),
            'last_login_at' => '',
            'created_at' => '2026-03-01 09:00:00',
            'updated_at' => '2026-03-01 09:00:00',
        ],
        [
            'id' => 'user-1004',
            'account' => 'ops.gu',
            'employee_no' => 'O1001',
            'name' => '顾宁',
            'title' => '运营负责人',
            'department' => '运营部',
            'role' => 'operations',
            'permissions' => [],
            'status' => 'active',
            'phone' => '13800000004',
            'email' => 'ops.gu@yfsoft.local',
            'hire_date' => '2024-08-12',
            'manager_id' => 'user-1001',
            'password_hash' => password_hash('Start@123', PASSWORD_DEFAULT),
            'last_login_at' => '',
            'created_at' => '2026-03-01 09:00:00',
            'updated_at' => '2026-03-01 09:00:00',
        ],
        [
            'id' => 'user-1005',
            'account' => 'product.wang',
            'employee_no' => 'PD1001',
            'name' => '王越',
            'title' => '业务分析',
            'department' => '产品部',
            'role' => 'viewer',
            'permissions' => [],
            'status' => 'active',
            'phone' => '13800000005',
            'email' => 'product.wang@yfsoft.local',
            'hire_date' => '2024-09-01',
            'manager_id' => 'user-1001',
            'password_hash' => password_hash('Start@123', PASSWORD_DEFAULT),
            'last_login_at' => '',
            'created_at' => '2026-03-01 09:00:00',
            'updated_at' => '2026-03-01 09:00:00',
        ],
        [
            'id' => 'user-1006',
            'account' => 'tech.zhou',
            'employee_no' => 'T1001',
            'name' => '周柯',
            'title' => '技术负责人',
            'department' => '技术部',
            'role' => 'tech',
            'permissions' => [],
            'status' => 'active',
            'phone' => '13800000006',
            'email' => 'tech.zhou@yfsoft.local',
            'hire_date' => '2024-05-09',
            'manager_id' => 'user-1001',
            'password_hash' => password_hash('Start@123', PASSWORD_DEFAULT),
            'last_login_at' => '',
            'created_at' => '2026-03-01 09:00:00',
            'updated_at' => '2026-03-01 09:00:00',
        ],
        [
            'id' => 'user-1007',
            'account' => 'service.liu',
            'employee_no' => 'S1001',
            'name' => '刘悦',
            'title' => '客服主管',
            'department' => '客服部',
            'role' => 'service',
            'permissions' => [],
            'status' => 'active',
            'phone' => '13800000007',
            'email' => 'service.liu@yfsoft.local',
            'hire_date' => '2024-11-05',
            'manager_id' => 'user-1001',
            'password_hash' => password_hash('Start@123', PASSWORD_DEFAULT),
            'last_login_at' => '',
            'created_at' => '2026-03-01 09:00:00',
            'updated_at' => '2026-03-01 09:00:00',
        ],
        [
            'id' => 'user-1008',
            'account' => 'leader.he',
            'employee_no' => 'M1001',
            'name' => '何浩',
            'title' => '经营负责人',
            'department' => '经营管理部',
            'role' => 'operations',
            'permissions' => [],
            'status' => 'active',
            'phone' => '13800000008',
            'email' => 'leader.he@yfsoft.local',
            'hire_date' => '2024-03-08',
            'manager_id' => 'user-1001',
            'password_hash' => password_hash('Start@123', PASSWORD_DEFAULT),
            'last_login_at' => '',
            'created_at' => '2026-03-01 09:00:00',
            'updated_at' => '2026-03-01 09:00:00',
        ],
    ],
    'audit_logs' => [],
    'transactions' => [
        [
            'id' => 'tx-1001',
            'date' => '2026-01-08',
            'type' => 'income',
            'category' => '项目预付款',
            'counterparty' => '星环科技',
            'amount' => 80000,
            'payment_method' => 'bank',
            'project_id' => 'prj-1001',
            'notes' => '企业官网重构项目首付款到账',
        ],
        [
            'id' => 'tx-1002',
            'date' => '2026-01-12',
            'type' => 'expense',
            'category' => '云资源',
            'counterparty' => '阿里云',
            'amount' => 6800,
            'payment_method' => 'bank',
            'project_id' => 'prj-1001',
            'notes' => '预发环境与对象存储费用',
        ],
        [
            'id' => 'tx-1003',
            'date' => '2026-02-03',
            'type' => 'expense',
            'category' => '工资发放',
            'counterparty' => '研发团队',
            'amount' => 48000,
            'payment_method' => 'bank',
            'project_id' => '',
            'notes' => '2 月上半月工资',
        ],
        [
            'id' => 'tx-1004',
            'date' => '2026-02-10',
            'type' => 'income',
            'category' => '订阅收入',
            'counterparty' => '教培 SaaS 客户',
            'amount' => 16800,
            'payment_method' => 'bank',
            'project_id' => 'prj-1003',
            'notes' => '标准版年费收款',
        ],
        [
            'id' => 'tx-1005',
            'date' => '2026-02-15',
            'type' => 'expense',
            'category' => '市场投放',
            'counterparty' => '巨量引擎',
            'amount' => 9000,
            'payment_method' => 'bank',
            'project_id' => '',
            'notes' => '春季获客投放',
        ],
        [
            'id' => 'tx-1006',
            'date' => '2026-03-05',
            'type' => 'income',
            'category' => '项目回款',
            'counterparty' => '北景数据',
            'amount' => 60000,
            'payment_method' => 'bank',
            'project_id' => 'prj-1002',
            'notes' => '客服工单 SaaS 一期回款',
        ],
        [
            'id' => 'tx-1007',
            'date' => '2026-03-08',
            'type' => 'expense',
            'category' => '外包测试',
            'counterparty' => '曜石测试',
            'amount' => 12000,
            'payment_method' => 'bank',
            'project_id' => 'prj-1002',
            'notes' => '兼容性与回归测试',
        ],
        [
            'id' => 'tx-1008',
            'date' => '2026-03-10',
            'type' => 'expense',
            'category' => '办公支出',
            'counterparty' => '办公用品',
            'amount' => 3200,
            'payment_method' => 'wechat',
            'project_id' => '',
            'notes' => '工位与会议室物料补充',
        ],
    ],
    'invoices' => [
        [
            'id' => 'inv-1001',
            'kind' => 'receivable',
            'title' => '企业官网重构一期尾款',
            'counterparty' => '星环科技',
            'amount' => 50000,
            'due_date' => '2026-03-25',
            'status' => 'pending',
            'project_id' => 'prj-1001',
            'notes' => '待客户验收后支付',
        ],
        [
            'id' => 'inv-1002',
            'kind' => 'payable',
            'title' => '第三方测试服务费',
            'counterparty' => '曜石测试',
            'amount' => 8000,
            'due_date' => '2026-03-22',
            'status' => 'pending',
            'project_id' => 'prj-1002',
            'notes' => '回归测试尾款',
        ],
        [
            'id' => 'inv-1003',
            'kind' => 'receivable',
            'title' => '财务 BI 看板续约',
            'counterparty' => '教培 SaaS 客户',
            'amount' => 20000,
            'due_date' => '2026-04-01',
            'status' => 'partial',
            'project_id' => 'prj-1003',
            'notes' => '已收定金，剩余款待续签',
        ],
    ],
    'projects' => [
        [
            'id' => 'prj-1001',
            'name' => '企业官网重构',
            'client' => '星环科技',
            'owner' => '张敏',
            'status' => 'delivery',
            'priority' => 'high',
            'budget' => 120000,
            'start_date' => '2026-01-05',
            'due_date' => '2026-03-28',
            'description' => '围绕品牌官网、招聘页和表单线索转化做重构升级。',
        ],
        [
            'id' => 'prj-1002',
            'name' => '客服工单 SaaS',
            'client' => '北景数据',
            'owner' => '张敏',
            'status' => 'active',
            'priority' => 'high',
            'budget' => 180000,
            'start_date' => '2026-02-18',
            'due_date' => '2026-04-30',
            'description' => '覆盖工单流转、知识库和客服绩效看板。',
        ],
        [
            'id' => 'prj-1003',
            'name' => '财务 BI 看板',
            'client' => '内部产品线',
            'owner' => '王越',
            'status' => 'planning',
            'priority' => 'medium',
            'budget' => 90000,
            'start_date' => '2026-03-03',
            'due_date' => '2026-05-20',
            'description' => '沉淀收入、成本、回款和经营分析的可视化面板。',
        ],
    ],
    'tasks' => [
        [
            'id' => 'task-1001',
            'project_id' => 'prj-1001',
            'title' => '交互稿确认',
            'assignee' => '王越',
            'status' => 'done',
            'priority' => 'high',
            'due_date' => '2026-02-05',
            'estimate_hours' => 18,
            'actual_hours' => 20,
        ],
        [
            'id' => 'task-1002',
            'project_id' => 'prj-1001',
            'title' => '前端联调',
            'assignee' => '周柯',
            'status' => 'doing',
            'priority' => 'high',
            'due_date' => '2026-03-20',
            'estimate_hours' => 30,
            'actual_hours' => 22,
        ],
        [
            'id' => 'task-1003',
            'project_id' => 'prj-1002',
            'title' => '需求梳理',
            'assignee' => '张敏',
            'status' => 'done',
            'priority' => 'high',
            'due_date' => '2026-02-25',
            'estimate_hours' => 12,
            'actual_hours' => 10,
        ],
        [
            'id' => 'task-1004',
            'project_id' => 'prj-1002',
            'title' => '权限模型设计',
            'assignee' => '周柯',
            'status' => 'todo',
            'priority' => 'medium',
            'due_date' => '2026-03-26',
            'estimate_hours' => 16,
            'actual_hours' => 0,
        ],
        [
            'id' => 'task-1005',
            'project_id' => 'prj-1003',
            'title' => '科目体系定义',
            'assignee' => '王越',
            'status' => 'doing',
            'priority' => 'medium',
            'due_date' => '2026-03-29',
            'estimate_hours' => 14,
            'actual_hours' => 6,
        ],
        [
            'id' => 'task-1006',
            'project_id' => 'prj-1003',
            'title' => '首版报表页面',
            'assignee' => '顾宁',
            'status' => 'todo',
            'priority' => 'medium',
            'due_date' => '2026-04-08',
            'estimate_hours' => 24,
            'actual_hours' => 0,
        ],
    ],
    'ops_projects' => [
        [
            'id' => 'ops-1001',
            'name' => '云帆 CRM App 拉新增长',
            'app_name' => '云帆 CRM',
            'app_version' => 'v2.8.0',
            'lifecycle_stage' => 'growth',
            'business_line' => 'CRM 产品线',
            'manager' => '顾宁',
            'client_owner' => '增长产品负责人',
            'core_metric' => '注册到试用转化率',
            'status' => 'running',
            'priority' => 'high',
            'budget' => 150000,
            'actual_cost' => 92000,
            'start_date' => '2026-03-01',
            'end_date' => '2026-04-20',
            'target' => '围绕 CRM App 完成新增拉新闭环，获得 1200 个有效试用注册，单个试用成本控制在 150 元以内。',
            'channel' => '信息流 / 短视频 / 应用商店投放',
            'project_id' => 'prj-1001',
            'description' => '围绕 CRM App 新版投放、落地页和埋点闭环推进增长，重点盯新增注册、试用转化和素材迭代节奏。',
        ],
        [
            'id' => 'ops-1002',
            'name' => '工单助手 App 留存续费',
            'app_name' => '工单助手',
            'app_version' => 'v3.2.1',
            'lifecycle_stage' => 'retention',
            'business_line' => '客户成功产品线',
            'manager' => '顾宁',
            'client_owner' => '客户成功负责人',
            'core_metric' => '30 日活跃率',
            'status' => 'running',
            'priority' => 'high',
            'budget' => 60000,
            'actual_cost' => 18000,
            'start_date' => '2026-03-05',
            'end_date' => '2026-05-10',
            'target' => '提升工单助手重点客户活跃与续费转化，完成 3 个重点客户续费，续费金额不少于 50 万。',
            'channel' => '客户拜访 / 续费脚本 / 运营培训',
            'project_id' => 'prj-1002',
            'description' => '围绕工单助手使用活跃、续费提醒和客户成功动作联动，建立留存数据和续费节奏台账。',
        ],
        [
            'id' => 'ops-1003',
            'name' => 'BI 看板 App 首发上线',
            'app_name' => 'BI 看板',
            'app_version' => 'v1.0.0',
            'lifecycle_stage' => 'launch',
            'business_line' => '数据产品线',
            'manager' => '王越',
            'client_owner' => 'BI 产品负责人',
            'core_metric' => '首周开通率',
            'status' => 'planning',
            'priority' => 'medium',
            'budget' => 30000,
            'actual_cost' => 5000,
            'start_date' => '2026-03-15',
            'end_date' => '2026-05-25',
            'target' => '完成首批 10 家试用客户开通上线，沉淀首发 onboarding 流程与复盘素材。',
            'channel' => '私域演示 / 客户试用 / 应用内触达',
            'project_id' => 'prj-1003',
            'description' => '围绕 BI 看板 App 首版上线做试运行，重点关注首发开通节奏、演示材料和首批反馈闭环。',
        ],
    ],
    'ops_milestones' => [
        [
            'id' => 'milestone-1001',
            'ops_project_id' => 'ops-1001',
            'title' => '首批素材与投放计划确认',
            'owner' => '顾宁',
            'due_date' => '2026-03-20',
            'status' => 'doing',
            'progress' => 70,
            'deliverable' => '素材排期表 / 渠道预算表',
            'notes' => '短视频素材已完成，搜索渠道文案还在确认。',
        ],
        [
            'id' => 'milestone-1002',
            'ops_project_id' => 'ops-1001',
            'title' => '线索转化页 AB 版本上线',
            'owner' => '周柯',
            'due_date' => '2026-03-28',
            'status' => 'pending',
            'progress' => 0,
            'deliverable' => 'AB 页面与埋点追踪',
            'notes' => '需要等设计稿与埋点方案确认。',
        ],
        [
            'id' => 'milestone-1003',
            'ops_project_id' => 'ops-1002',
            'title' => '重点客户续费清单定版',
            'owner' => '顾宁',
            'due_date' => '2026-03-22',
            'status' => 'review',
            'progress' => 90,
            'deliverable' => '客户续费节奏表',
            'notes' => '销售经理正在确认最终名单。',
        ],
        [
            'id' => 'milestone-1004',
            'ops_project_id' => 'ops-1003',
            'title' => '试用客户 onboarding 完成',
            'owner' => '王越',
            'due_date' => '2026-04-02',
            'status' => 'pending',
            'progress' => 10,
            'deliverable' => '试用客户名单与培训材料',
            'notes' => '需要先输出 onboarding 流程与演示材料。',
        ],
    ],
    'ops_updates' => [
        [
            'id' => 'report-1001',
            'ops_project_id' => 'ops-1001',
            'report_date' => '2026-03-18',
            'owner' => '顾宁',
            'summary' => '已确认两轮投放节奏，短视频素材 6 套完成 4 套。',
            'result' => '预计本周可以开第一轮测试投放。',
            'next_actions' => '补齐搜索广告文案，联动开发确认转化埋点。',
            'blockers' => '搜索广告落地页还未交付。',
        ],
        [
            'id' => 'report-1002',
            'ops_project_id' => 'ops-1002',
            'report_date' => '2026-03-17',
            'owner' => '顾宁',
            'summary' => '3 个重点客户中已有 2 个进入商务沟通。',
            'result' => '预计下周能锁定首个续费方案。',
            'next_actions' => '补充客户使用数据和续费案例。',
            'blockers' => '其中 1 个客户仍在等交付侧验收说明。',
        ],
        [
            'id' => 'report-1003',
            'ops_project_id' => 'ops-1003',
            'report_date' => '2026-03-16',
            'owner' => '王越',
            'summary' => '已梳理试用客户名单，正在准备演示材料。',
            'result' => '本周先完成 onboarding 话术与演示模板。',
            'next_actions' => '确定首批试用时间表。',
            'blockers' => '产品页文案还未确认。',
        ],
    ],
    'ops_risks' => [
        [
            'id' => 'risk-1001',
            'ops_project_id' => 'ops-1001',
            'title' => '搜索广告落地页交付延期',
            'type' => 'issue',
            'level' => 'high',
            'status' => 'tracking',
            'owner' => '周柯',
            'due_date' => '2026-03-21',
            'impact' => '首轮搜索投放无法按计划开启，可能影响线索目标。',
            'action_plan' => '先使用简化页兜底，正式版完成后切换。',
        ],
        [
            'id' => 'risk-1002',
            'ops_project_id' => 'ops-1002',
            'title' => '续费案例素材不完整',
            'type' => 'risk',
            'level' => 'medium',
            'status' => 'open',
            'owner' => '顾宁',
            'due_date' => '2026-03-24',
            'impact' => '销售沟通缺少说服材料，可能影响续费推进。',
            'action_plan' => '本周内补齐客户使用结果和案例摘要。',
        ],
        [
            'id' => 'risk-1003',
            'ops_project_id' => 'ops-1003',
            'title' => '试用客户需求口径存在变化',
            'type' => 'change',
            'level' => 'low',
            'status' => 'tracking',
            'owner' => '王越',
            'due_date' => '2026-03-27',
            'impact' => '试用方案和培训节奏需要做调整。',
            'action_plan' => '先整理需求差异，评估是否拆成两个 onboarding 版本。',
        ],
    ],
    'ops_releases' => [
        [
            'id' => 'release-1001',
            'ops_project_id' => 'ops-1001',
            'version' => 'v2.8.1',
            'title' => '拉新落地页埋点与线索回传',
            'status' => 'testing',
            'owner' => '周柯',
            'release_date' => '2026-03-24',
            'channel' => '灰度 30%',
            'tech_ticket_ids' => ['tech-1001', 'tech-1002'],
            'service_ticket_ids' => ['service-1001'],
            'verification_summary' => '灰度环境已验证注册通知、线索回传和企业微信字段同步，待 30% 灰度观察。',
            'customer_sync_status' => 'pending',
            'customer_sync_note' => '客服待灰度稳定后统一回告星环科技。',
            'release_result' => '',
            'release_notes' => '补齐注册、试用、来源埋点，并同步企业微信线索字段。',
            'rollback_plan' => '保留 v2.8.0 配置并支持 10 分钟内回切。',
            'rollback_ready' => true,
            'notes' => '运营会在灰度阶段同步验证投放转化。',
            'created_at' => '2026-03-18 11:00:00',
            'created_by' => 'user-1006',
            'created_by_name' => '周柯',
            'updated_at' => '2026-03-19 09:30:00',
            'updated_by' => 'user-1004',
            'updated_by_name' => '顾宁',
        ],
        [
            'id' => 'release-1002',
            'ops_project_id' => 'ops-1002',
            'version' => 'v3.2.2',
            'title' => '续费提醒分批策略上线',
            'status' => 'ready',
            'owner' => '周柯',
            'release_date' => '2026-03-21',
            'channel' => '全量发布',
            'tech_ticket_ids' => ['tech-1003'],
            'service_ticket_ids' => ['service-1002'],
            'verification_summary' => '预发布环境已完成策略脚本、发送节奏和模板校验，待生产窗口执行。',
            'customer_sync_status' => 'pending',
            'customer_sync_note' => '版本上线后由客服同步新的续费提醒话术和配置说明。',
            'release_result' => '',
            'release_notes' => '新增 7 天、3 天、当天三段提醒，并支持客户分层。',
            'rollback_plan' => '保留旧策略模板，必要时恢复单模板发送。',
            'rollback_ready' => true,
            'notes' => '客服会同步准备新版本使用话术。',
            'created_at' => '2026-03-17 16:20:00',
            'created_by' => 'user-1006',
            'created_by_name' => '周柯',
            'updated_at' => '2026-03-19 10:10:00',
            'updated_by' => 'user-1006',
            'updated_by_name' => '周柯',
        ],
        [
            'id' => 'release-1003',
            'ops_project_id' => 'ops-1003',
            'version' => 'v1.0.1',
            'title' => '首发图表筛选修复热补丁',
            'status' => 'planned',
            'owner' => '周柯',
            'release_date' => '2026-03-20',
            'channel' => '指定试用客户',
            'tech_ticket_ids' => ['tech-1004'],
            'service_ticket_ids' => ['service-1003'],
            'verification_summary' => '修复补丁已在测试环境通过筛选切换、缓存清理和图表渲染验证。',
            'customer_sync_status' => 'pending',
            'customer_sync_note' => '发布后第一时间回告首发试用客户，并跟进演示窗口。',
            'release_result' => '',
            'release_notes' => '修复筛选切换后图表空白问题，并补充缓存逻辑。',
            'rollback_plan' => '保留热补丁开关，可按客户维度关闭。',
            'rollback_ready' => true,
            'notes' => '客服与运营需在发布后第一时间回访试用客户。',
            'created_at' => '2026-03-19 09:40:00',
            'created_by' => 'user-1006',
            'created_by_name' => '周柯',
            'updated_at' => '2026-03-19 10:00:00',
            'updated_by' => 'user-1008',
            'updated_by_name' => '何浩',
        ],
    ],
    'ops_materials' => [
        [
            'id' => 'material-1001',
            'ops_project_id' => 'ops-1001',
            'title' => 'CRM 拉新投放SOP',
            'category' => 'manual',
            'owner' => '顾宁',
            'version_tag' => '2026.03',
            'applicable_versions' => 'v2.8.x',
            'expires_on' => '',
            'archive_status' => 'active',
            'replacement_material_id' => '',
            'download_name' => 'crm-growth-playbook.txt',
            'download_url' => '/downloads/crm-growth-playbook.txt',
            'updated_on' => '2026-03-18',
            'notes' => '给运营和客服统一使用的拉新投放、线索回收与异常回告说明。',
            'created_at' => '2026-03-18 15:00:00',
            'created_by' => 'user-1004',
            'created_by_name' => '顾宁',
            'updated_at' => '2026-03-18 15:00:00',
            'updated_by' => 'user-1004',
            'updated_by_name' => '顾宁',
        ],
        [
            'id' => 'material-1002',
            'ops_project_id' => 'ops-1002',
            'title' => '工单助手续费话术FAQ',
            'category' => 'faq',
            'owner' => '刘悦',
            'version_tag' => 'v3.2.2',
            'applicable_versions' => 'v3.2.x',
            'expires_on' => '2026-03-18',
            'archive_status' => 'active',
            'replacement_material_id' => '',
            'download_name' => 'ticket-assistant-faq.txt',
            'download_url' => '/downloads/ticket-assistant-faq.txt',
            'updated_on' => '2026-03-19',
            'notes' => '客服续费回访、异议处理和升级研发前的排查脚本。',
            'created_at' => '2026-03-19 09:30:00',
            'created_by' => 'user-1007',
            'created_by_name' => '刘悦',
            'updated_at' => '2026-03-19 09:30:00',
            'updated_by' => 'user-1007',
            'updated_by_name' => '刘悦',
        ],
        [
            'id' => 'material-1003',
            'ops_project_id' => 'ops-1003',
            'title' => 'BI 看板首发培训脚本',
            'category' => 'training',
            'owner' => '王越',
            'version_tag' => '首发版',
            'applicable_versions' => 'v1.0.0-beta',
            'expires_on' => '',
            'archive_status' => 'archived',
            'replacement_material_id' => '',
            'download_name' => 'bi-onboarding-script.txt',
            'download_url' => '/downloads/bi-onboarding-script.txt',
            'updated_on' => '2026-03-19',
            'notes' => '试用客户演示顺序、Bug回告模板和发版后复访脚本。',
            'created_at' => '2026-03-19 10:20:00',
            'created_by' => 'user-1005',
            'created_by_name' => '王越',
            'updated_at' => '2026-03-19 10:20:00',
            'updated_by' => 'user-1005',
            'updated_by_name' => '王越',
        ],
    ],
    'tech_tickets' => [
        [
            'id' => 'tech-1001',
            'ops_project_id' => 'ops-1001',
            'project_id' => 'prj-1001',
            'title' => '注册落地页埋点丢失导致转化数据不准',
            'type' => 'bug',
            'status' => 'doing',
            'priority' => 'high',
            'severity' => 'high',
            'source' => 'operations',
            'app_module' => '注册转化页',
            'app_version' => 'v2.8.0',
            'owner' => '周柯',
            'reporter' => '顾宁',
            'due_date' => '2026-03-22',
            'impact' => '运营无法准确统计投放转化率，影响拉新预算分配。',
            'solution_plan' => '补齐注册、试用、渠道来源埋点并回溯验证日志。',
            'estimate_hours' => 12,
            'actual_hours' => 6,
            'notes' => '需要和 BI 看板一起联调事件名称。',
        ],
        [
            'id' => 'tech-1002',
            'ops_project_id' => 'ops-1001',
            'project_id' => 'prj-1001',
            'title' => '试用注册流程增加企业微信线索回填',
            'type' => 'feature',
            'status' => 'queued',
            'priority' => 'high',
            'severity' => 'medium',
            'source' => 'operations',
            'app_module' => '注册流程',
            'app_version' => 'v2.8.0',
            'owner' => '周柯',
            'reporter' => '顾宁',
            'due_date' => '2026-03-29',
            'impact' => '线索入 CRM 依赖人工补录，运营跟进效率低。',
            'solution_plan' => '新增企业微信字段回填与来源标签同步。',
            'estimate_hours' => 16,
            'actual_hours' => 0,
            'notes' => '等产品确认字段映射规则后进入开发。',
        ],
        [
            'id' => 'tech-1003',
            'ops_project_id' => 'ops-1002',
            'project_id' => 'prj-1002',
            'title' => '续费提醒消息中心支持分批触达策略',
            'type' => 'improvement',
            'status' => 'testing',
            'priority' => 'medium',
            'severity' => 'medium',
            'source' => 'product',
            'app_module' => '消息中心',
            'app_version' => 'v3.2.1',
            'owner' => '周柯',
            'reporter' => '王越',
            'due_date' => '2026-03-23',
            'impact' => '当前提醒方式单一，客户续费节奏难以分层管理。',
            'solution_plan' => '增加 7 天、3 天、当天三段提醒模板与开关。',
            'estimate_hours' => 10,
            'actual_hours' => 9,
            'notes' => '测试完成后即可随 v3.2.2 发布。',
        ],
        [
            'id' => 'tech-1004',
            'ops_project_id' => 'ops-1003',
            'project_id' => 'prj-1003',
            'title' => '筛选项切换后图表状态丢失',
            'type' => 'bug',
            'status' => 'pending',
            'priority' => 'high',
            'severity' => 'blocker',
            'source' => 'customer',
            'app_module' => '图表首页',
            'app_version' => 'v1.0.0',
            'owner' => '周柯',
            'reporter' => '王越',
            'due_date' => '2026-03-21',
            'impact' => '首发客户无法连续查看核心指标，影响上线体验。',
            'solution_plan' => '修复筛选状态缓存与图表重新渲染逻辑。',
            'estimate_hours' => 8,
            'actual_hours' => 0,
            'notes' => '需要优先于首批试用客户演示前修复。',
        ],
    ],
    'service_tickets' => [
        [
            'id' => 'service-1001',
            'ticket_no' => 'CS20260318001',
            'source' => 'customer',
            'customer' => '星环科技',
            'contact_name' => '王琳',
            'contact_phone' => '13910000001',
            'channel' => 'wechat',
            'category' => 'bug',
            'title' => '注册试用后短信通知没有收到',
            'summary' => '客户在云帆 CRM App 内提交试用后，没有收到短信通知，已经影响销售跟进。',
            'status' => 'escalated',
            'priority' => 'high',
            'assignee' => '刘悦',
            'opened_at' => '2026-03-18 10:15:00',
            'last_follow_up_at' => '2026-03-19 09:20:00',
            'resolve_due_at' => '2026-03-20 18:00:00',
            'next_action' => '等待研发修复后回访客户确认',
            'customer_notified' => false,
            'customer_notified_to' => '王琳',
            'customer_notified_channel' => 'wechat',
            'customer_notified_at' => '',
            'customer_feedback_result' => '',
            'customer_confirmed' => false,
            'customer_confirmed_at' => '',
            'customer_confirmation_note' => '',
            'ops_project_id' => 'ops-1001',
            'project_id' => 'prj-1001',
            'tech_ticket_id' => 'tech-1001',
            'notes' => '客服已同步销售和运营，优先级拉高。',
            'created_at' => '2026-03-18 10:15:00',
            'created_by' => 'user-1007',
            'created_by_name' => '刘悦',
            'updated_at' => '2026-03-19 09:20:00',
            'updated_by' => 'user-1007',
            'updated_by_name' => '刘悦',
        ],
        [
            'id' => 'service-1002',
            'ticket_no' => 'CS20260318002',
            'source' => 'training',
            'customer' => '北京数据',
            'contact_name' => '赵敏',
            'contact_phone' => '13910000002',
            'channel' => 'phone',
            'category' => 'usage',
            'title' => '续费提醒配置不会设置',
            'summary' => '客户希望分批次发送续费提醒，但不会配置策略，需要客服协助。',
            'status' => 'processing',
            'priority' => 'medium',
            'assignee' => '刘悦',
            'opened_at' => '2026-03-18 14:30:00',
            'last_follow_up_at' => '2026-03-19 08:45:00',
            'resolve_due_at' => '2026-03-21 12:00:00',
            'next_action' => '安排远程演示并同步知识库说明',
            'customer_notified' => true,
            'customer_notified_to' => '赵敏',
            'customer_notified_channel' => 'phone',
            'customer_notified_at' => '2026-03-19 08:45:00',
            'customer_feedback_result' => '已电话回告客户先走远程演示和 FAQ 说明，客户接受当前安排。',
            'customer_confirmed' => true,
            'customer_confirmed_at' => '2026-03-19 09:00:00',
            'customer_confirmation_note' => '客户确认按明天下午远程演示推进。',
            'ops_project_id' => 'ops-1002',
            'project_id' => 'prj-1002',
            'tech_ticket_id' => '',
            'notes' => '不需要研发介入，先由客服做陪跑。',
            'created_at' => '2026-03-18 14:30:00',
            'created_by' => 'user-1007',
            'created_by_name' => '刘悦',
            'updated_at' => '2026-03-19 08:45:00',
            'updated_by' => 'user-1007',
            'updated_by_name' => '刘悦',
        ],
        [
            'id' => 'service-1003',
            'ticket_no' => 'CS20260319001',
            'source' => 'leader',
            'customer' => '首发试用客户',
            'contact_name' => '陈雪',
            'contact_phone' => '13910000003',
            'channel' => 'app',
            'category' => 'complaint',
            'title' => '筛选切换后图表空白',
            'summary' => 'BI 看板首发客户反馈筛选切换后图表空白，影响本周演示体验。',
            'status' => 'escalated',
            'priority' => 'high',
            'assignee' => '刘悦',
            'opened_at' => '2026-03-19 09:10:00',
            'last_follow_up_at' => '2026-03-19 09:50:00',
            'resolve_due_at' => '2026-03-20 11:00:00',
            'next_action' => '盯发布局并在修复后补做客户说明',
            'customer_notified' => false,
            'customer_notified_to' => '陈雪',
            'customer_notified_channel' => 'app',
            'customer_notified_at' => '',
            'customer_feedback_result' => '',
            'customer_confirmed' => false,
            'customer_confirmed_at' => '',
            'customer_confirmation_note' => '',
            'ops_project_id' => 'ops-1003',
            'project_id' => 'prj-1003',
            'tech_ticket_id' => 'tech-1004',
            'notes' => '客户情绪比较敏感，需要经营负责人同步关注。',
            'created_at' => '2026-03-19 09:10:00',
            'created_by' => 'user-1007',
            'created_by_name' => '刘悦',
            'updated_at' => '2026-03-19 09:50:00',
            'updated_by' => 'user-1008',
            'updated_by_name' => '何浩',
        ],
        [
            'id' => 'service-1004',
            'ticket_no' => 'CS20260319002',
            'source' => 'sales',
            'customer' => '教育 SaaS 客户',
            'contact_name' => '林峰',
            'contact_phone' => '13910000004',
            'channel' => 'email',
            'category' => 'billing',
            'title' => '续费账单明细需要补发',
            'summary' => '客户已收到付款提醒，但需要分项账单说明和上一期对账截图。',
            'status' => 'waiting_customer',
            'priority' => 'medium',
            'assignee' => '刘悦',
            'opened_at' => '2026-03-19 11:25:00',
            'last_follow_up_at' => '2026-03-19 14:00:00',
            'resolve_due_at' => '2026-03-22 18:00:00',
            'next_action' => '等待客户确认账单明细后关闭工单',
            'customer_notified' => true,
            'customer_notified_to' => '林峰',
            'customer_notified_channel' => 'email',
            'customer_notified_at' => '2026-03-19 14:00:00',
            'customer_feedback_result' => '已补发账单分项和对账截图，客户回复先内部确认后再反馈。',
            'customer_confirmed' => false,
            'customer_confirmed_at' => '',
            'customer_confirmation_note' => '',
            'ops_project_id' => 'ops-1002',
            'project_id' => 'prj-1002',
            'tech_ticket_id' => '',
            'notes' => '如客户继续追问自动对账能力，再转成功能建议。',
            'created_at' => '2026-03-19 11:25:00',
            'created_by' => 'user-1007',
            'created_by_name' => '刘悦',
            'updated_at' => '2026-03-19 14:00:00',
            'updated_by' => 'user-1007',
            'updated_by_name' => '刘悦',
        ],
    ],
    'service_ticket_updates' => [
        [
            'id' => 'service-update-1001',
            'service_ticket_id' => 'service-1001',
            'type' => 'status',
            'visibility' => 'internal',
            'content' => '已确认短信网关异常，问题转给研发排查，销售和运营已同步。',
            'status' => 'escalated',
            'next_action' => '等待研发修复后安排客户回访。',
            'created_at' => '2026-03-19 09:20:00',
            'created_by' => 'user-1007',
            'created_by_name' => '刘悦',
            'updated_at' => '2026-03-19 09:20:00',
            'updated_by' => 'user-1007',
            'updated_by_name' => '刘悦',
        ],
        [
            'id' => 'service-update-1002',
            'service_ticket_id' => 'service-1002',
            'type' => 'follow_up',
            'visibility' => 'customer',
            'content' => '已与客户电话沟通，确认先由客服远程演示配置路径，无需立即转研发。',
            'status' => 'processing',
            'next_action' => '发送 FAQ 文档并预约明天下午远程演示。',
            'created_at' => '2026-03-19 08:45:00',
            'created_by' => 'user-1007',
            'created_by_name' => '刘悦',
            'updated_at' => '2026-03-19 08:45:00',
            'updated_by' => 'user-1007',
            'updated_by_name' => '刘悦',
        ],
        [
            'id' => 'service-update-1003',
            'service_ticket_id' => 'service-1003',
            'type' => 'leader',
            'visibility' => 'leader',
            'content' => '经营负责人要求在明天上午演示前完成修复方案，并准备客户说明口径。',
            'status' => 'escalated',
            'next_action' => '盯研发热补丁发布时间，准备发版后回告。',
            'created_at' => '2026-03-19 09:50:00',
            'created_by' => 'user-1008',
            'created_by_name' => '何浩',
            'updated_at' => '2026-03-19 09:50:00',
            'updated_by' => 'user-1008',
            'updated_by_name' => '何浩',
        ],
        [
            'id' => 'service-update-1004',
            'service_ticket_id' => 'service-1004',
            'type' => 'internal',
            'visibility' => 'internal',
            'content' => '财务已补充账单分项明细，客服等待客户确认是否还需要自动对账能力说明。',
            'status' => 'waiting_customer',
            'next_action' => '收到客户确认后决定关闭还是转成功能建议。',
            'created_at' => '2026-03-19 14:00:00',
            'created_by' => 'user-1007',
            'created_by_name' => '刘悦',
            'updated_at' => '2026-03-19 14:00:00',
            'updated_by' => 'user-1007',
            'updated_by_name' => '刘悦',
        ],
    ],
    'ai' => [
        'settings' => [
            'provider_name' => 'OpenAI Compatible',
            'base_url' => '',
            'api_key' => '',
            'model' => '',
            'temperature' => 0.2,
            'system_prompt' => '你是云帆软件的经营与财务助理。你只能基于给定业务数据进行分析，优先输出可执行建议、风险提醒、资金结论和项目影响，不要编造不存在的数据。',
        ],
        'conversation' => [
            [
                'role' => 'assistant',
                'content' => 'AI 工作台已启用。先在“模型设置”里填写兼容 OpenAI 协议的 Base URL、API Key 和模型名称，然后就可以直接对财务、项目、APP 运营和技术协同数据提问。',
                'created_at' => '2026-03-19 00:00:00',
            ],
        ],
        'workspace' => [
            'finance_window' => true,
            'projects_window' => true,
            'tasks_window' => true,
            'ai_window' => true,
        ],
    ],
];
